/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import dao.DaoCliente;
import dao.DaoCompra;
import dao.DaoFornecedor;
import dao.DaoItemCompra;
import dao.DaoItemVenda;
import dao.DaoVenda;
import java.awt.Component;
import java.sql.SQLException;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import javax.swing.text.NumberFormatter;

/**
 *
 * @author ManutencaoEtec
 */
public class FrmCompras extends javax.swing.JInternalFrame {

    ArrayList<DaoFornecedor> fo;
    ArrayList<DaoItemCompra> it;
    NumberFormatter nfPreco;
    MaskFormatter mfData;

    boolean alterar = false;
    boolean incluir = false;
    boolean alterarItem = false;
    boolean IncluirItem = false;
    boolean encerrado = false;

    static boolean visible = false;

    public static boolean getVis() {
        return visible;
    }

    public void setVis(boolean v) {
        visible = v;
    }

    /**
     * Creates new form FrmVendas
     */
    public FrmCompras() throws ParseException, SQLException, ClassNotFoundException {
        initComponents();
        DecimalFormat df = new DecimalFormat("R$ #,###,##0.00;-R$ #,###,##0.00");
        nfPreco = new NumberFormatter(df);
        nfPreco.setValueClass(Double.class);
        try {
            DaoFornecedor fornecedor = new DaoFornecedor();
            fo = new ArrayList<DaoFornecedor>();
            fo.addAll(fornecedor.pesquisar(fornecedor));
            for (DaoFornecedor daoFo : fo) {
                cmbFornecedor.addItem(daoFo.getCodFor());
            }
        //    cmbFornecedor.setSelectedIndex(0);
            it = new ArrayList<DaoItemCompra>();
            mfData = new MaskFormatter("##/##/####");
            mfData.setPlaceholderCharacter('_');
            mfData.setValueContainsLiteralCharacters(true);
            mfData.setValueClass(String.class);
            DefaultFormatterFactory dffData = new DefaultFormatterFactory(mfData);
            txtDataCompra.setFormatterFactory(dffData);
            txtDataEntrega.setFormatterFactory(dffData);

        } catch (ParseException e) {
            throw new ParseException("Ocorreu um erro no Formulário de vendas: \n" + e.getMessage(), 0);
        } catch (SQLException e) {
            throw new SQLException("Ocorreu um erro no Formulário de Vendas: \n" + e.getMessage());
        } catch (ClassNotFoundException e) {
            throw new ClassNotFoundException("Ocorreu um erro no Formulário de vendas: \n" + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        pnlCompras = new javax.swing.JPanel();
        btnIncluir = new javax.swing.JButton();
        pnlCamposCompra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNumCompra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDataCompra = new javax.swing.JFormattedTextField();
        scpObs = new javax.swing.JScrollPane();
        txtObs = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbFornecedor = new javax.swing.JComboBox();
        txtFantasia = new javax.swing.JTextField();
        txtDataEntrega = new javax.swing.JFormattedTextField();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        btnGravar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        scpVendas = new javax.swing.JScrollPane();
        tblCompras = new javax.swing.JTable();
        pnlItens = new javax.swing.JPanel();
        btnIncluirItem = new javax.swing.JButton();
        btnAlterarItem = new javax.swing.JButton();
        btnExcluirItem = new javax.swing.JButton();
        btnPesquisarItem = new javax.swing.JButton();
        btnEncerrar = new javax.swing.JButton();
        scpItens = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        pnlTotal = new javax.swing.JPanel();
        txtTotalCompra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Controle de Compras");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel7.setText("Compras");

        jLabel8.setText("Detalhes");

        pnlCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIncluir.setText("Incluir");
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        jLabel2.setText("Núm. Compra:");

        txtNumCompra.setEnabled(false);

        jLabel3.setText("Data Compra:");

        jLabel4.setText("Obs.:");

        txtDataCompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDataCompra.setEnabled(false);
        txtDataCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataCompraActionPerformed(evt);
            }
        });

        txtObs.setColumns(20);
        txtObs.setRows(5);
        txtObs.setEnabled(false);
        scpObs.setViewportView(txtObs);

        jLabel5.setText("Fornecedor:");

        jLabel6.setText("Data Entrega:");

        cmbFornecedor.setMaximumRowCount(1000);
        cmbFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFornecedorActionPerformed(evt);
            }
        });

        txtFantasia.setEnabled(false);
        txtFantasia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFantasiaActionPerformed(evt);
            }
        });

        txtDataEntrega.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        txtDataEntrega.setEnabled(false);

        javax.swing.GroupLayout pnlCamposCompraLayout = new javax.swing.GroupLayout(pnlCamposCompra);
        pnlCamposCompra.setLayout(pnlCamposCompraLayout);
        pnlCamposCompraLayout.setHorizontalGroup(
            pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlCamposCompraLayout.createSequentialGroup()
                        .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlCamposCompraLayout.createSequentialGroup()
                                .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(scpObs))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlCamposCompraLayout.setVerticalGroup(
            pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNumCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(cmbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtDataEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCamposCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(scpObs, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.setEnabled(false);
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        tblCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Compra", "Fornecedor", "Fantasia", "Data da Compra", "Entrega em", "Obs"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCompras.getTableHeader().setResizingAllowed(false);
        tblCompras.getTableHeader().setReorderingAllowed(false);
        tblCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComprasMouseClicked(evt);
            }
        });
        scpVendas.setViewportView(tblCompras);

        javax.swing.GroupLayout pnlComprasLayout = new javax.swing.GroupLayout(pnlCompras);
        pnlCompras.setLayout(pnlComprasLayout);
        pnlComprasLayout.setHorizontalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpVendas)
                    .addGroup(pnlComprasLayout.createSequentialGroup()
                        .addComponent(pnlCamposCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(pnlComprasLayout.createSequentialGroup()
                        .addComponent(btnIncluir)
                        .addGap(53, 53, 53)
                        .addComponent(btnAlterar)
                        .addGap(53, 53, 53)
                        .addComponent(btnExcluir)
                        .addGap(53, 53, 53)
                        .addComponent(btnPesquisar)
                        .addGap(53, 53, 53)
                        .addComponent(btnGravar)
                        .addGap(53, 53, 53)
                        .addComponent(btnCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSair)))
                .addContainerGap())
        );
        pnlComprasLayout.setVerticalGroup(
            pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlComprasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlComprasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(btnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar)
                    .addComponent(btnGravar)
                    .addComponent(btnCancelar)
                    .addComponent(btnSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCamposCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scpVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlItens.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnIncluirItem.setText("Incluir");
        btnIncluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirItemActionPerformed(evt);
            }
        });

        btnAlterarItem.setText("Alterar");
        btnAlterarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarItemActionPerformed(evt);
            }
        });

        btnExcluirItem.setText("Excluir");
        btnExcluirItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirItemActionPerformed(evt);
            }
        });

        btnPesquisarItem.setText("Pesquisar");
        btnPesquisarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarItemActionPerformed(evt);
            }
        });

        btnEncerrar.setText("Encerrar");
        btnEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncerrarActionPerformed(evt);
            }
        });

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Descrição", "Quantidade", "Preço Unitário", "SubTotal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblItens.getTableHeader().setResizingAllowed(false);
        tblItens.getTableHeader().setReorderingAllowed(false);
        scpItens.setViewportView(tblItens);

        javax.swing.GroupLayout pnlItensLayout = new javax.swing.GroupLayout(pnlItens);
        pnlItens.setLayout(pnlItensLayout);
        pnlItensLayout.setHorizontalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scpItens)
                    .addGroup(pnlItensLayout.createSequentialGroup()
                        .addComponent(btnIncluirItem)
                        .addGap(42, 42, 42)
                        .addComponent(btnAlterarItem)
                        .addGap(42, 42, 42)
                        .addComponent(btnExcluirItem)
                        .addGap(42, 42, 42)
                        .addComponent(btnPesquisarItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEncerrar)))
                .addContainerGap())
        );
        pnlItensLayout.setVerticalGroup(
            pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlItensLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlItensLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluirItem)
                    .addComponent(btnAlterarItem)
                    .addComponent(btnExcluirItem)
                    .addComponent(btnPesquisarItem)
                    .addComponent(btnEncerrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scpItens, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlTotal.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtTotalCompra.setEditable(false);
        txtTotalCompra.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtTotalCompra.setForeground(new java.awt.Color(153, 51, 0));
        txtTotalCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCompraActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabel9.setText("Total Compra:");

        javax.swing.GroupLayout pnlTotalLayout = new javax.swing.GroupLayout(pnlTotal);
        pnlTotal.setLayout(pnlTotalLayout);
        pnlTotalLayout.setHorizontalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTotalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnlTotalLayout.setVerticalGroup(
            pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTotalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotalCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCompras, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(pnlItens, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCompras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComprasMouseClicked
        // TODO add your handling code here:
        if (tblCompras.getRowCount() >= 0) {
            DaoItemCompra item = new DaoItemCompra();
            item.setNumCompra((Integer) tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
            item.setCodPro(0);
            try {
                txtTotalCompra.setText("R$ 0,00");
                atualizaTableItens(item.pesquisar(item));
                
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco de dados:\n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro no driver de conexão:\n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ocorreu um erro: " + e.getMessage(), "erro:", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_tblComprasMouseClicked

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // TODO add your handling code here:
        formWindowClosing(null);
        setVis(false);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed
        // TODO add your handling code here:
        DaoFornecedor fornecedor = new DaoFornecedor();
        try {
            habilitaBotoes(false, pnlCompras);
            habilitaComponentes(false, pnlItens);
            habilitaComponentes(true, pnlCamposCompra);
            cmbFornecedorActionPerformed(null);
            txtObs.setEnabled(true);
            limpaCampos(pnlCamposCompra);
            txtObs.setText("");
            txtFantasia.setText(fo.get(cmbFornecedor.getSelectedIndex()).getFantasia());
            incluir = true;
            txtNumCompra.setEnabled(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(),
                    "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIncluirActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        DaoCompra compra = new DaoCompra();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
            try {
                compra.setNumCompra(Integer.valueOf(txtNumCompra.getText()));
            } catch (Exception e) {
            }
            try {
                compra.setCodFor(Integer.valueOf(cmbFornecedor.getSelectedItem().toString()));
            } catch (Exception e) {
            }
            compra.setDataCompra(sdf.parse(txtDataCompra.getText()));
            compra.setDataEntrega(sdf.parse(txtDataEntrega.getText()));
            compra.setObs(txtObs.getText());
            if (incluir) {
                compra.incluir();
            }
            if (alterar) {
                compra.alterar();
            }
            btnCancelarActionPerformed(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnGravarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        DaoCompra compra = new DaoCompra();
        DaoItemCompra item = new DaoItemCompra();
        compra.setNumCompra(0);
        try {
            if (compra.pesquisar(compra).isEmpty()) {
                //JOptionPane.showMessageDialog(null, "Não há compras cadastradas!", "Atenção:", JOptionPane.WARNING_MESSAGE);
                limpaTable(tblCompras);
            } else {
                atualizaTableCompras(compra.pesquisar(compra));
                tblCompras.addRowSelectionInterval(0, 0);
                item.setNumCompra((Integer) tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
                item.setCodPro((int) tblCompras.getValueAt(tblCompras.getSelectedRow(), 1));
                if (!item.pesquisar(item).isEmpty()) {
                    atualizaTableItens(item.pesquisar(item));

                }
            }
            habilitaComponentes(false, pnlCamposCompra);
            txtObs.setEnabled(false);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco de dados:\n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no driver de conexão:\n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_formWindowOpened

    private void cmbFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFornecedorActionPerformed
        // TODO add your handling code here:
        txtFantasia.setText(fo.get(cmbFornecedor.getSelectedIndex()).getFantasia());
    }//GEN-LAST:event_cmbFornecedorActionPerformed

    private void atualizaTableItens(ArrayList<DaoItemCompra> itens) {
        limpaTable(tblItens);
        double total = 0;
        if (!itens.isEmpty()) {

            DefaultTableModel dadosItens = (DefaultTableModel) tblItens.getModel();
            String Linha[] = new String[]{"", "", "", "", ""};
            try {
                int posicao = -1;
                for (DaoItemCompra item : itens) {
                    posicao++;
                    dadosItens.addRow(Linha);
                    dadosItens.setValueAt(item.getCodPro(), posicao, 0);
                    dadosItens.setValueAt(item.getDescricao(), posicao, 1);
                    dadosItens.setValueAt(item.getQuantidade(), posicao, 2);
                    dadosItens.setValueAt(nfPreco.valueToString(item.getPrecoUnit()), posicao, 3);
                    dadosItens.setValueAt(nfPreco.valueToString(item.getSubtotal()), posicao, 4);
                    total = total + item.getSubtotal();
                }
                txtTotalCompra.setText(nfPreco.valueToString(total));
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            }
        } else {
        }
    }

    private void habilitaBotoes(boolean hab, JPanel panel) {
        for (Component jcomp : panel.getComponents()) {
            if (jcomp instanceof JButton) {
                jcomp.setEnabled(hab);
                if ((jcomp.getAccessibleContext().getAccessibleName().equals("Cancelar"))) {
                    jcomp.setEnabled(!hab);
                }
                if ((jcomp.getAccessibleContext().getAccessibleName().equals("Gravar"))) {
                    jcomp.setEnabled(!hab);
                }
            }
        }
    }

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        formWindowOpened(null);
        habilitaBotoes(true, pnlCompras);
        limpaCampos(pnlCamposCompra);
        txtObs.setText("");
        habilitaComponentes(false, pnlCamposCompra);
        habilitaComponentes(true, pnlItens);
        txtObs.setEnabled(false);
        incluir = false;
        alterar = false;
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed
        // TODO add your handling code here:
        DaoFornecedor fornecedor = new DaoFornecedor();
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        try {
        habilitaBotoes(false, pnlCompras);
        habilitaComponentes(false, pnlItens);
        habilitaComponentes(true, pnlCamposCompra);
        fo.addAll(fornecedor.pesquisar(fornecedor));
        for (DaoFornecedor daoFo : fo) {
                cmbFornecedor.addItem(daoFo.getCodFor());
            }
            txtNumCompra.setEnabled(false);
            txtObs.setEnabled(true);
            if (tblCompras.getRowCount() > 0) {
                int posLinha = tblCompras.getSelectedRow();
                if (posLinha >= 0) {
                    txtNumCompra.setText(tblCompras.getValueAt(posLinha, 0).toString());
                    for (DaoFornecedor daoFo : fo) {
                        if (daoFo.getCodFor()== Integer.valueOf(tblCompras.getValueAt(posLinha, 1).toString())) {
                            cmbFornecedor.setSelectedIndex(fo.indexOf(daoFo));
                        }
                    }

                    txtFantasia.setText(tblCompras.getValueAt(posLinha, 1).toString());
                    txtDataCompra.setValue(tblCompras.getValueAt(posLinha, 3).toString());
                    txtDataEntrega.setValue(tblCompras.getValueAt(posLinha, 4).toString());
                    txtObs.setText(tblCompras.getValueAt(posLinha,5).toString());
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione uma compra para alterar!", "Erro:", JOptionPane.ERROR_MESSAGE);
                    btnCancelarActionPerformed(null);
                }
                
            } else {
                JOptionPane.showMessageDialog(null, "Não há compras cadastrados ainda!", "Erro:", JOptionPane.ERROR_MESSAGE);
                btnCancelarActionPerformed(null);
            }
            txtDataCompra.requestFocus();
            alterar = true;
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no Banco de dados:\n", "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no driver de conexão:\n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAlterarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        try {
            if (tblCompras.getSelectedRow() >= 0) {
                Object[] options = {"Sim", "Não"};
                if ((JOptionPane.showOptionDialog(this, "Deseja mesmo APAGAR a compra selecionada?", "Aviso:", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[1])) == JOptionPane.YES_OPTION) {
                    DaoCompra dc = new DaoCompra();
                    DaoItemCompra di = new DaoItemCompra();
                    di.setNumCompra(Integer.valueOf(tblCompras.getValueAt(tblCompras.getSelectedRow(), 0).toString()));
                    dc.setNumCompra(di.getNumCompra());
                    di.excluir();
                    dc.excluir();
                    if (dc.excluir()) {
                        JOptionPane.showMessageDialog(null, "Compra excluida com sucesso!", "Exclusão:", JOptionPane.INFORMATION_MESSAGE);
                    }
                    formWindowOpened(null);
                }
            } formWindowOpened(null);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        DaoCompra dc = new DaoCompra();
        DaoItemCompra dic = new DaoItemCompra();
        try {
            String numCompraTemp = JOptionPane.showInputDialog(this, "Informe o número da compra desejada: \n (Zero para visualizar todos novamente)", "Pesquisar", JOptionPane.QUESTION_MESSAGE);
            if (numCompraTemp != null) {
                dc.setNumCompra(Integer.valueOf(numCompraTemp));
                dic.setNumCompra(dc.getNumCompra());

                if (dc.pesquisar(dc).isEmpty()) {
                    JOptionPane.showMessageDialog(null, "A compra não foi encontrada", "Erro:", JOptionPane.ERROR_MESSAGE);
                } else {
                    if (dic.getNumCompra()< 1) {
                        dc.setNumCompra(0);
                        dic.setNumCompra(dc.getNumCompra());
                    }
                    atualizaTableCompras(dc.pesquisar(dc));
                    tblCompras.setRowSelectionInterval(0, 0);
                    tblComprasMouseClicked(null);
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Operação Cancelada! \nOcorreu um erro no valor informado para o Número da compra: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnIncluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirItemActionPerformed
        // TODO add your handling code here:
        try {
            DaoItemCompra item = new DaoItemCompra();
            if (item.pesquisar(item).isEmpty()) {
                item.setNumCompra((int) tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
                item = FrmItemCompra.showItemCompra(item);
                for (DaoItemCompra daoIt : it) {
                    if (daoIt.getCodPro() == item.getCodPro()) {
                        JOptionPane.showMessageDialog(null, "O PRODUTO já está cadastrado nessa compra!", "Erro:", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }

                if (item != null) {
                    it.add(item);
                    atualizaTableItens(it);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não é possivel ADICIONAR itens nessa compra: \nA compra está ENCERRADA!", "Erro:", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnIncluirItemActionPerformed

    private void btnAlterarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarItemActionPerformed
        // TODO add your handling code here:
        try {
            DaoItemCompra item = new DaoItemCompra();
            item.setNumCompra((int) tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
            if (item.pesquisar(item).isEmpty()) {
                if (tblItens.getSelectedRow() >= 0) {
                    if (item != null) {
                        item = FrmItemCompra.showItemCompra(item);
                        item.alterar();
                        it.set(tblItens.getSelectedRow(), item);
                        atualizaTableItens(it);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione primeiro o item que deseja alterar!", "Erro:", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não é possível ALTERAR itens nessa compra:\nA compra está ENCERRADA!", "Erro:", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAlterarItemActionPerformed

    private void btnExcluirItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirItemActionPerformed
        // TODO add your handling code here:
        try {
            Object[] botoes = {" Sim ", " Não "};
            DaoItemCompra item = new DaoItemCompra();
            item.setNumCompra((int) tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
            if (item.pesquisar(item).isEmpty()) {
                if (tblItens.getSelectedRow() >= 0) {
                    item = it.get(tblItens.getSelectedRow());
                    if (JOptionPane.showOptionDialog(null, "Deseja mesmo APAGAR o item?", "Atenção:", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, botoes, botoes[1]) == JOptionPane.YES_OPTION) {
                        it.remove(item);
                        atualizaTableItens(it);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Selecione primeiro o item que deseja excluir!", "Erro:", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Não é possível EXCLUIR itens nessa compra:\nA compra está ENCERRADA!", "Erro:", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExcluirItemActionPerformed

    private void btnPesquisarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarItemActionPerformed
        // TODO add your handling code here:
        DaoCompra dc = new DaoCompra();
        DaoItemCompra dic = new DaoItemCompra();
        try {
            String codProTemp;
            codProTemp = JOptionPane.showInputDialog(this, "Informe o código do produto desejado: \n (Zero para visualizar todos novamente)", "Pesquisa:", JOptionPane.QUESTION_MESSAGE);
            if (codProTemp != null) {
                dic.setNumCompra((int)tblCompras.getValueAt(tblCompras.getSelectedRow(), 0));
                dic.setCodPro(Integer.valueOf(codProTemp));
                dic.pesquisarItem(dic);
                
                if (dic.pesquisar(dic).isEmpty()) {
                    JOptionPane.showMessageDialog(null, "O produto não foi encontrado!", "Erro:", JOptionPane.ERROR_MESSAGE);
                } else {
                    atualizaTableItens(dic.pesquisar(dic));
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (ClassNotFoundException e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Operação cancelada \nOcorreu um erro no valor informado para o Código do produto: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnPesquisarItemActionPerformed

    private void btnEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncerrarActionPerformed
        // TODO add your handling code here:
        if (!it.isEmpty()) {
            try {
                if (JOptionPane.showConfirmDialog(this, "Deseja mesmo ENCERRAR a compra!", "Atenção", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
                    for (DaoItemCompra daoItem : it) {
                        daoItem.incluir();
                    }
                    it.clear();
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro no DB: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            } catch (ClassNotFoundException e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro de classe: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnEncerrarActionPerformed

    private void txtTotalCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCompraActionPerformed

    private void txtFantasiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFantasiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFantasiaActionPerformed

    private void txtDataCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataCompraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataCompraActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        formWindowOpened(null);
    }//GEN-LAST:event_formInternalFrameOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCompras.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FrmCompras().setVisible(true);
                } catch (ParseException ex) {
                    Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(FrmCompras.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    private void limpaTable(JTable table) {
        DefaultTableModel dtm = (DefaultTableModel) table.getModel();
        while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
    }

    private void atualizaTableCompras(ArrayList<DaoCompra> compras) {
        limpaTable(tblCompras);
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        if (compras.isEmpty()) {
            //JOptionPane.showMessageDialog(null, "Não foram encontradas COMPRAS no banco de dados.", "Atenção:", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel dadosCompras = (DefaultTableModel) tblCompras.getModel();
            String Linha[] = new String[]{"", "", "", "", "", ""};
            try {
                int posicao = -1;
                for (DaoCompra compra : compras) {
                    posicao++;
                    dadosCompras.addRow(Linha);
                    dadosCompras.setValueAt(compra.getNumCompra(), posicao, 0);
                    dadosCompras.setValueAt(compra.getCodFor(), posicao, 1);
                    dadosCompras.setValueAt(compra.getFantasia(), posicao, 2);
                    dadosCompras.setValueAt(sdf.format(compra.getDataCompra()), posicao, 3);
                    dadosCompras.setValueAt(sdf.format(compra.getDataEntrega()), posicao, 4);
                    dadosCompras.setValueAt(compra.getObs(), posicao, 5);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro: " + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void habilitaComponentes(boolean hab, JComponent container) {
        for (Component jcomp : container.getComponents()) {
            jcomp.setEnabled(hab);
        }
    }

    private void limpaCampos(JComponent container) {
        for (Component jcomp : container.getComponents()) {
            if (jcomp instanceof JTextField) {
                ((JTextField) jcomp).setText("");
            }
            if (jcomp instanceof JComboBox) {
                ((JComboBox) jcomp).setSelectedIndex(0);
            }
            if (jcomp instanceof JFormattedTextField) {
                ((JFormattedTextField) jcomp).setValue("");
            }
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnAlterarItem;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEncerrar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnExcluirItem;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnIncluirItem;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnPesquisarItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox cmbFornecedor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnlCamposCompra;
    private javax.swing.JPanel pnlCompras;
    private javax.swing.JPanel pnlItens;
    private javax.swing.JPanel pnlTotal;
    private javax.swing.JScrollPane scpItens;
    private javax.swing.JScrollPane scpObs;
    private javax.swing.JScrollPane scpVendas;
    private javax.swing.JTable tblCompras;
    private javax.swing.JTable tblItens;
    private javax.swing.JFormattedTextField txtDataCompra;
    private javax.swing.JFormattedTextField txtDataEntrega;
    private javax.swing.JTextField txtFantasia;
    private javax.swing.JTextField txtNumCompra;
    private javax.swing.JTextArea txtObs;
    private javax.swing.JTextField txtTotalCompra;
    // End of variables declaration//GEN-END:variables
}
