/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComponent;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author LuizFlavio
 */
public class FrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public FrmMenu() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        ActionListener tmrHoraAction = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                SimpleDateFormat minhaData = new SimpleDateFormat("dd/MM/yyyy - HH:mm:ss");
                lblHora.setText(minhaData.format(new Date()));
            }
        };
        Timer tmrHora = new Timer(1000, tmrHoraAction);
        tmrHora.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpTelas = new javax.swing.JDesktopPane();
        jToolBar1 = new javax.swing.JToolBar();
        btnClientes = new javax.swing.JButton();
        btnProdutos = new javax.swing.JButton();
        btnVendas = new javax.swing.JButton();
        btnFornecedores = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        btnSair = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblHora = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmiFrmClientes = new javax.swing.JMenuItem();
        jmiFrmProduto = new javax.swing.JMenuItem();
        jmiFrmVendas = new javax.swing.JMenuItem();
        jmiFrmFornecedor = new javax.swing.JMenuItem();
        jmiFrmCompras = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiSair = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmiCliente = new javax.swing.JMenuItem();
        jmiProduto = new javax.swing.JMenuItem();
        jmiVenda = new javax.swing.JMenuItem();
        jmiFornecedor = new javax.swing.JMenuItem();
        jmiCompra = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Menu");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jdpTelas.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jdpTelasLayout = new javax.swing.GroupLayout(jdpTelas);
        jdpTelas.setLayout(jdpTelasLayout);
        jdpTelasLayout.setHorizontalGroup(
            jdpTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        jdpTelasLayout.setVerticalGroup(
            jdpTelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 425, Short.MAX_VALUE)
        );

        jToolBar1.setRollover(true);

        btnClientes.setText("Clientes");
        btnClientes.setFocusable(false);
        btnClientes.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnClientes.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnClientes);

        btnProdutos.setText("Produtos");
        btnProdutos.setFocusable(false);
        btnProdutos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProdutos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutosActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProdutos);

        btnVendas.setText("Vendas");
        btnVendas.setToolTipText("");
        btnVendas.setFocusable(false);
        btnVendas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVendas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVendasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnVendas);

        btnFornecedores.setText("Fornecedor");
        btnFornecedores.setFocusable(false);
        btnFornecedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFornecedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFornecedoresActionPerformed(evt);
            }
        });
        jToolBar1.add(btnFornecedores);

        btnCompras.setText("Compras");
        btnCompras.setFocusable(false);
        btnCompras.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCompras.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCompras);
        jToolBar1.add(jSeparator2);

        btnSair.setText("Sair");
        btnSair.setFocusable(false);
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSair);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblHora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblHora, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
        );

        jMenu1.setMnemonic('a');
        jMenu1.setText("Arquivo");
        jMenu1.setToolTipText("");

        jmiFrmClientes.setText("Cadastrar Clientes");
        jmiFrmClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrmClientesActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFrmClientes);

        jmiFrmProduto.setText("Cadastrar Produtos");
        jmiFrmProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrmProdutoActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFrmProduto);

        jmiFrmVendas.setText("Cadastrar Vendas");
        jmiFrmVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrmVendasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFrmVendas);

        jmiFrmFornecedor.setText("Cadastrar Fornecedores");
        jmiFrmFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrmFornecedorActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFrmFornecedor);

        jmiFrmCompras.setText("Cadastrar Compras");
        jmiFrmCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFrmComprasActionPerformed(evt);
            }
        });
        jMenu1.add(jmiFrmCompras);
        jMenu1.add(jSeparator1);

        jmiSair.setMnemonic('r');
        jmiSair.setText("Sair");
        jmiSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSairActionPerformed(evt);
            }
        });
        jMenu1.add(jmiSair);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('r');
        jMenu2.setText("Relatório");

        jmiCliente.setText("Cliente");
        jmiCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiClienteActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCliente);

        jmiProduto.setText("Produto");
        jmiProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiProdutoActionPerformed(evt);
            }
        });
        jMenu2.add(jmiProduto);

        jmiVenda.setText("Venda");
        jmiVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVendaActionPerformed(evt);
            }
        });
        jMenu2.add(jmiVenda);

        jmiFornecedor.setText("Fornecedor");
        jmiFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFornecedorActionPerformed(evt);
            }
        });
        jMenu2.add(jmiFornecedor);

        jmiCompra.setText("Compra");
        jmiCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiCompraActionPerformed(evt);
            }
        });
        jMenu2.add(jmiCompra);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('u');
        jMenu3.setText("Ajuda");

        mnuSobre.setMnemonic('s');
        mnuSobre.setText("Sobre");
        mnuSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSobreActionPerformed(evt);
            }
        });
        jMenu3.add(mnuSobre);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpTelas)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpTelas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        try {
            Object[] btn = {"  Sim  ", "  Não  "};
            if (JOptionPane.showOptionDialog(this, "Deseja mesmo sair?", "Aviso:",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE, null, //new ImageIcon("") ,
                    btn, btn[1]) == JOptionPane.YES_OPTION) {
                //Encerra a JVM atual e consequentemente o sistema nela rodando
                System.exit(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void jmiFrmClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrmClientesActionPerformed
        boolean naoTem = true;
        try {
            for (JInternalFrame tela : jdpTelas.getAllFrames()) {
                if (tela instanceof FrmClientes) {
                    tela.setIcon(false);
                    tela.toFront();
                    tela.requestFocus();
                    naoTem = false;
                }
            }
            if (naoTem) {
                FrmClientes f1 = new FrmClientes();
                jdpTelas.add(f1);
                f1.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFrmClientesActionPerformed

    private void jmiFrmProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrmProdutoActionPerformed
        boolean naoTem = true;
        try {
            for (JInternalFrame tela : jdpTelas.getAllFrames()) {
                if (tela instanceof FrmProduto) {
                    tela.setIcon(false);
                    tela.toFront();
                    tela.requestFocus();
                    naoTem = false;
                }
            }
            if (naoTem) {
                FrmProduto f2 = new FrmProduto();
                jdpTelas.add(f2);
                f2.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFrmProdutoActionPerformed

    private void jmiFrmVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrmVendasActionPerformed
        boolean naoTem = true;
        try {
            for (JInternalFrame tela : jdpTelas.getAllFrames()) {
                if (tela instanceof FrmVendas) {
                    tela.setIcon(false);
                    tela.toFront();
                    tela.requestFocus();
                    naoTem = false;
                }
            }
            if (naoTem) {
                FrmVendas f3 = new FrmVendas();
                jdpTelas.add(f3);
                f3.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFrmVendasActionPerformed

    private void btnVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVendasActionPerformed
        jmiFrmVendasActionPerformed(null);
    }//GEN-LAST:event_btnVendasActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        jmiFrmClientesActionPerformed(null);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFornecedoresActionPerformed
        jmiFrmFornecedorActionPerformed(null);
    }//GEN-LAST:event_btnFornecedoresActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        jmiSairActionPerformed(null);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jmiSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSairActionPerformed
        formWindowClosing(null);
    }//GEN-LAST:event_jmiSairActionPerformed

    private void btnProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutosActionPerformed
        jmiFrmProdutoActionPerformed(null);
    }//GEN-LAST:event_btnProdutosActionPerformed

    private void jmiFrmFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrmFornecedorActionPerformed
        boolean naoTem = true;
        try {
            for (JInternalFrame tela : jdpTelas.getAllFrames()) {
                if (tela instanceof FrmFornecedor) {
                    tela.setIcon(false);
                    tela.toFront();
                    tela.requestFocus();
                    naoTem = false;
                }
            }
            if (naoTem) {
                FrmFornecedor f4 = new FrmFornecedor();
                jdpTelas.add(f4);
                f4.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFrmFornecedorActionPerformed

    private void jmiFrmComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFrmComprasActionPerformed
        boolean naoTem = true;
        try {
            for (JInternalFrame tela : jdpTelas.getAllFrames()) {
                if (tela instanceof FrmCompras) {
                    tela.setIcon(false);
                    tela.toFront();
                    tela.requestFocus();
                    naoTem = false;
                }
            }
            if (naoTem) {
                FrmCompras f5 = new FrmCompras();
                jdpTelas.add(f5);
                f5.setVisible(true);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro:\n" + e.getMessage(), "Erro no encerramento:",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFrmComprasActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
        jmiFrmComprasActionPerformed(null);
    }//GEN-LAST:event_btnComprasActionPerformed

    private void mnuSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSobreActionPerformed
        try{
            FrmAbout item = new FrmAbout(this, rootPaneCheckingEnabled);
            item.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro: \n" + e.getMessage(), "Erro:", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_mnuSobreActionPerformed

    private void jmiClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiClienteActionPerformed
        try {
            VisualizaRpt.geraRelatorio("RptClientes.jasper", null, "Relatório de Clientes");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ERRO:\n" + 
                    e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiClienteActionPerformed

    private void jmiProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiProdutoActionPerformed
        try {
            VisualizaRpt.geraRelatorio("RptProdutos.jasper", null, "Relatório de Produtos");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ERRO:\n" + 
                    e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_jmiProdutoActionPerformed

    private void jmiVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVendaActionPerformed
        try {
            VisualizaRpt.geraRelatorio("RptVendas.jasper", null, "Relatório de Vendas");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ERRO:\n" + 
                    e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiVendaActionPerformed

    private void jmiFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFornecedorActionPerformed
       try {
            VisualizaRpt.geraRelatorio("RptFornecedores.jasper", null, "Relatório de Fornecedores");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ERRO:\n" + 
                    e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiFornecedorActionPerformed

    private void jmiCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiCompraActionPerformed
       try {
            VisualizaRpt.geraRelatorio("RptCompras.jasper", null, "Relatório de Compras");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um ERRO:\n" + 
                    e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jmiCompraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnFornecedores;
    private javax.swing.JButton btnProdutos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnVendas;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JDesktopPane jdpTelas;
    private javax.swing.JMenuItem jmiCliente;
    private javax.swing.JMenuItem jmiCompra;
    private javax.swing.JMenuItem jmiFornecedor;
    private javax.swing.JMenuItem jmiFrmClientes;
    private javax.swing.JMenuItem jmiFrmCompras;
    private javax.swing.JMenuItem jmiFrmFornecedor;
    private javax.swing.JMenuItem jmiFrmProduto;
    private javax.swing.JMenuItem jmiFrmVendas;
    private javax.swing.JMenuItem jmiProduto;
    private javax.swing.JMenuItem jmiSair;
    private javax.swing.JMenuItem jmiVenda;
    private javax.swing.JLabel lblHora;
    private javax.swing.JMenuItem mnuSobre;
    // End of variables declaration//GEN-END:variables
}
